import { Link, useParams } from "react-router-dom";
import type { ReactNode } from "react";
import PipelineStages from "../components/PipelineStages";
import ResourceList from "../components/ResourceList";
import TerraformViewer from "../components/TerraformViewer";
import PolicyPanel from "../components/PolicyPanel";
import TerraformPlanPanel from "../components/TerraformPlanPanel";
import HealingTimeline from "../components/HealingTimeline";
import { useRunPolling } from "../hooks/useRunPolling";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="bg-pilot-panel border border-pilot-border rounded-xl p-6">
      <h2 className="text-lg font-semibold mb-4">{title}</h2>
      {children}
    </section>
  );
}

const GENERATION_METHOD_LABEL: Record<string, { label: string; className: string }> = {
  vertex_llm: { label: "Generated by Vertex AI / Gemini", className: "bg-emerald-900/40 border-emerald-700 text-emerald-300" },
  mock_llm: { label: "Generated by offline Mock LLM (no Vertex credentials configured)", className: "bg-sky-900/40 border-sky-700 text-sky-300" },
  deterministic_fallback: {
    label: "Generated by deterministic fallback (LLM path failed or produced invalid output)",
    className: "bg-amber-900/40 border-amber-700 text-amber-300",
  },
  unknown: { label: "Generation method unknown", className: "bg-slate-800 border-slate-700 text-slate-300" },
};

export default function RunDetails() {
  const { runId } = useParams<{ runId: string }>();
  const { run, error } = useRunPolling(runId);

  return (
    <div className="max-w-5xl mx-auto px-4 py-10 space-y-6">
      <Link to="/" className="text-sm text-sky-400 hover:underline">
        &larr; Back to dashboard
      </Link>

      <header>
        <h1 className="text-xl font-bold font-mono">{runId}</h1>
        {error && <p className="text-rose-400 text-sm mt-1">{error}</p>}
      </header>

      <Section title="Pipeline">
        <PipelineStages run={run} />
      </Section>

      <Section title="Request">
        <p className="text-sm">{run?.request || "Loading..."}</p>
        {run?.constraints && <p className="text-xs text-slate-500 mt-2">Constraints: {run.constraints}</p>}
      </Section>

      <Section title="Architecture">
        <ResourceList resources={run?.resources || []} />
      </Section>

      <Section title="Terraform">
        {run?.terraform_generation_method && (
          <div
            className={`mb-4 inline-block px-3 py-1 rounded border text-xs font-semibold ${
              (GENERATION_METHOD_LABEL[run.terraform_generation_method] || GENERATION_METHOD_LABEL.unknown).className
            }`}
          >
            {(GENERATION_METHOD_LABEL[run.terraform_generation_method] || GENERATION_METHOD_LABEL.unknown).label}
          </div>
        )}
        <TerraformViewer files={run?.terraform_files || {}} />
      </Section>

      <Section title="Policy">
        <PolicyPanel policy={run?.policy_results} />
      </Section>

      <Section title="Terraform Plan">
        <TerraformPlanPanel plan={run?.terraform_plan} />
      </Section>

      <Section title="Healing">
        <HealingTimeline history={run?.heal_history || []} />
      </Section>

      {run?.errors && run.errors.length > 0 && (
        <Section title="Errors">
          <ul className="text-sm text-rose-400 space-y-1 font-mono">
            {run.errors.map((e, idx) => (
              <li key={idx}>{e}</li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}
